---
- raw: yum -y install python-simplejson
  register: yum_result
  ignore_errors: true
  become: true
- raw: apt-get -y install python-simplejson
  register: apt_result
  ignore_errors: true
  become: true
- raw: which python
